README.md, azure-providers.js
Add support for /drop/location endpoint
=> Add /drop/locations

README.md, azure-providers.js, example.html
In some instances (My Account Orders or Order Review) The Cart OrderLine
modification methods (increment, decrement, delete) are not necessary.
We created AzureOrders, AzureOrder and AzureOrderLines factories
to keep the Cart OrderLine methods separate from base OrderLines.
=> azure-providers.js: AzureOrders, AzureOrder and AzureOrderLine Factories

README.md, azure-providers.js
Add support for registration, confirmation, and resend confirmation endpoints.
=> Registration endpoints

README.md, azure-providers.js, bower.json
Adds Algolia Search Client to the AzureAPI object.
=> Algolia Search Integration

circle.yml
**Please don't merge yet, testing**
=> Add ESLint syntax checking for CircleCI.

azure-providers.js
These are POSTing data with payloads, so they should be using the
payload headers.
=> AzureAPI: Use payloadHeaders for all $http.post calls

azure-providers.js
=> Wait for orderLine.$delete to resolve before calling _calculateOrder.

README.md, azure-providers.js
Required to make a payment on an outstanding balance using the payment
api.
=> add payment model

azure-providers.js
selects the active cart based on the following order:
old website cart
drop cart
parcel carrier cart
=> modify default cart selection

README.md, azure-providers.js
See azurestandard/api-spec#125.
=> Changed 'cart' status to 'open'

azure-providers.js
Details in the commit message.
=> Fix double algolia request in AzureProduct

azure-providers.js
Resolves azurestandard/website#642.
Resolves azurestandard/website#637.
=> Prevent request for category id 0.

README.md, azure-providers.js
Adds support for multiple emails. 
Required for website [PR 1068](https://github.com/azurestandard/website/pull/1068).
=> Add multiple email support

README.md, azure-providers.js
see azurestandard/api-spec#167
and azurestandard/beehive#2321
=> add models for bartender

.editorconfig, .jsbeautifyrc, .jshintrc, README.md, azure-providers.js, bower.json, example.html
- This removes obsolete services and algolia functionality that are not being used by either website or internal-website
- Renames some variables for greater clarity
- Cleans up some code that was causing JSHint warnings
=> Remove obsolete services and algolia functionality

azure-providers.js
Also reduces nesting and formats file.
=> Add packaged-product old action

README.md, bower.json, package.json
Also formats the readme file and bumps the version.
=> Update readme with packaged-product old action

README.md, azure-providers.js
For https://github.com/azurestandard/api-spec/pull/247, implemented via https://github.com/azurestandard/beehive/pull/4127.
=> Add order-frequency-segment endpoint

azure-providers.js
Test with https://github.com/azurestandard/website/pull/2695.
=> Allow GET params on posts

README.md, azure-providers.js
I've gone with `update` for the method name, since that seems the most logical. Happy to rename it if there's something better.
=> Add PATCH support

azure-providers.js
Needed for the frontend part of https://github.com/azurestandard/beehive/pull/5884.
=> Add order-promo-code model
