example.html

packaged_product wasn't defined, so change's weren't doing anything
useful in selectPackaging.  The fixed version works like this:
1. User selects an option in the drop-down
2. Angular sets product.code (because it's ng-model)
3. Angular triggers ng-change
4. selectPackaging fires with the new code
I'd broken this in ac2181f8 (azure-providers.js: Add PackagedProduct
and update associated APIs, 2015-02-23).  That was a big change, and I
broke a few of other things too, grep the logs for ac2181f ;).

example.html: Fix selectPackaging call in packaging-select widget

---

README.md
azure-providers.js
example.html

Too much Python predisposes me to write [`lower_case_with_underscores`][1], I'd used it a number of times in this repository.  However, the JavaScript community seems to prefer [camelCase][2].  This PR updates everything turned up by:
$ git grep '[a-zA-Z0-9]_'
so I'm pretty sure I've caught all occurrences.  There are quite a few commits, because almost every commit is single call to `sed`, which should make the changes easier to review if you want to look through them on a per-commit basis.
This is based on #8 (which removes an existing `packaged_product` that was broken, this PR is just about style), so I wouldn't bother reviewing this until #8 has landed.
[1]: https://www.python.org/dev/peps/pep-0008/#descriptive-naming-styles
[2]: …

Convert lower_case to camelCase to match JavaScript style

---

azure-providers.js

This looks like a copy/paste error from c4eb73c1 (AzureOrders,
AzureOrder and AzureOrderLine Factories, 2015-07-30), which removed:
if (order.drop) {
this.drop = AzureAPI.drop.get({
id: order.drop,
});
}
and added:
Order.prototype._drop = function() {
this.drop = AzureAPI.drop.get({
id: this.order.drop,
person: this.order.customer
});
};
The drop ID should be all we need to get a drop ;).

azure-providers.js: Drop 'person' parameter from AzureAPI.drop.get call

---

README.md
azure-providers.js
example.html

Catch up with azurestandard/api-spec@2ab80437 (public.json: Add
packagedProduct.favorite boolean and annotate-person parameter,
2015-06-08) which just landed in our implementation
(azurestandard/beehive@550d56e, Merge pull request #1211 from
azurestandard/tk/api-filter-person, 2015-09-24).
After this commit:
$ git grep person.*: | grep -v filter-person
only returns matches for 'AzureAPI.person', the "'person': 'people'"
entry in _plurals, and the "person: person" entry in the
AzureAPI.register implementation (which is POSTing data, and not
asking for filtered search results).

Update 'person' -> 'filter-person'

---

README.md
azure-providers.js

Catch up with azurestandard/api-spec@01861207 (public.json: Add
person.price-level and a multi-level price object, 2015-09-16,
azurestandard/api-spec#29) and azurestandard/api-spec@9658ee1
(public.json: Make orderLine.price a total dollar value,
azurestandard/api-spec#36).  Details in the commit messages.
This is part of the client-side adjustment for
azurestandard/beehive#1244.

Adjust to the new API pricing model

---

README.md
azure-providers.js
example.html

Instead of using function arguments arguments for the first level of keys.  This way you don't have to remember/lookup the argument order.
This is a backwards-incompatible change to those APIs, but it allows for more direct binding between the API spec and the caller.  On the one hand, that means we don't need to update this library if the API shuffles its expected fields.  On the other hand, that means we can't buffer callers when the API shuffles its expected fields (but shuffling will probably include semantic changes, and callers will have to update to handle those anyway).
Spun off from azurestandard/website#83, pulling in azurestandard/azure-angular-providers@99d1c2c from tk/refactor which was based on a change in azurestandard/azure-angular-providers@eb018dc in jh/refactor, part of …

AzureAPI: Pass $http.post data through directly

---

example.html

Avoid the following error (made readable by using non-.min versions of
the Angular scripts):
14:50:22.936 Error: [$injector:modulerr] Failed to instantiate module AzureApp due to:
[$injector:modulerr] Failed to instantiate module azureProviders due to:
[$injector:modulerr] Failed to instantiate module algoliasearch due to:
[$injector:nomod] Module 'algoliasearch' is not available! You
either misspelled the module name or forgot to load it. If
registering a module ensure that you specify the dependencies as
the second argument.
http://errors.angularjs.org/1.3.0/$injector/nomod?p0=algoliasearch
minErr/<@http://ajax.googleapis.com/ajax/libs/angularjs/1.3.0/angular.js:80:12
module/<@http://ajax.googleapis.com/ajax/libs/angularjs/1.3.0/angular.js:1797:1 …

example.html: Import algoliasearch.angular.min.js from jsDelivr

---

README.md
azure-providers.js

This allows us to perform actions after a cart has been created.

Add promise to Carts.prototype.createCart

---

README.md

This was in a01ca4c2 (AzureAPI: Add AzureAPIProvider.algoliaIndices to
configure index names, 2015-09-14) but was dropped accidentally in the
reroll process that resulted in in the merged bf845121 (AzureAPI: Add
Algolia client indexes to models, 2015-09-24, #12).

README: Add an algolia-search URL reference

---

README.md
azure-providers.js

We are not using a packaged-product index in Algolia, but we do have a brand index, so this simply replaces the packaged-product index declaration with a declaration for the brand index.

replace packaged-product algolia index with brand index

---

README.md

This parenthetical is trying to explain why we need an AzureProduct
reference here, when we already have an existing product-like field.
It was just using the wrong name for the product-like field.
The old language landed in 115dd62c (README.md: Document the
AzureCarts interface, 2015-01-07) describing
Cart.Orderlines[].productObject.  But since 7f5299c1
(azure-providers.js: Add an OrderLine class wrapping order-line
resources, 2015-02-05) added an OrderLine class (instead of stuffing
information into the API object) the 'product' reference has been
outdated.

azure-providers.js: Fix product -> orderLine['packaged-product'] reference

---

README.md
azure-providers.js

Customers can shop and edit on a placed order that is pre-cutoff.
Once cutoff has passed, the order no longer shows up in their list of possible carts.

AzureCarts: Allow shopping on pre-cutoff, placed orders

---

azure-providers.js

This is required to use the .browseAll() method that is being used for loading all drops, plus using https is just a good idea.

force algolia to use https

---

README.md
azure-providers.js

Access to the Algolia client object is required to perform
multiple-index searches.

expose algolia client object

---

README.md
azure-providers.js

The frontend requires more information on a drop's coordinator then just an ID.
This commit returns a person $resource for the drop. Note, if there are more than one coordinator, only the first coordinator's information is returned.

azure-providers.js: Expose coordinator information in AzureOrder

---

azure-providers.js

The API has specified .payment-method since azurestandard/api-spec@7e8b6814 (public.json: Add order.checkout-payment, 2015-10-02, azurestandard/api-spec#39).  The implemented backend had been using .method since azurestandard/beehive@34e7a19c (apps/api/views/order.py: Add order.payment fields, 2015-04-23), but is catching up with the API spec in azurestandard/beehive@d5c3cdc8 (apps/api/views/order.py: Fix .method -> .payment-method, 2016-03-21, azurestandard/beehive#1636).
Don't merge this until azurestandard/beehive#1636 lands ;).

AzureOrder: Catch up with .checkout-payment.payment-method

---

example.html

Angular [v1.4.4][1] [deprecated][2] [them][3] in favor of the generic
`$promise.then` (and presumably `.catch`).
[1]: https://github.com/angular/angular.js/blob/v1.4.4/CHANGELOG.md#features
[2]: https://docs.angularjs.org/api/ng/service/$http#deprecation-notice
[3]: https://github.com/angular/angular.js/pull/12112

example.html: Migrate from deprecated .success and .error

---

azure-providers.js

Resolves #43.
When the user changes the quantity of an order line on the cart page, [the `save()` method of the `orderLine` object is called](https://github.com/azurestandard/website/blob/67c1965190f2e8a62661a427d60d0b8fb97f539c/app/views/partials/cart_product_rows.html#L26). If it's a local cart, nothing happens because the method is not implemented on the `AzureLocalCarts` version of `OrderLine`. This implementation of the missing save method calculates the orderLine based on the quantity entered and recalculates the cart totals.

Implementation of missing save() function of AzureLocalCarts OrderLine.

---

azure-providers.js

In order to allow customer service to modify orders after cutoff and
before verification, do not remove post-cutoff orders in AzureCarts.

do not filter cutoff times on carts

---

azure-providers.js

Objects that are expected to be in algolia may not be there. In such cases, fall back to retrieving the object from the API.
For example, discontinued products are not in algolia but consumers of azure-angular-providers still need the product information.
[Examples of use cases](https://github.com/azurestandard/website/issues/388#issuecomment-221128204) where this is needed came up in azurestandard/website#388.

Fallback to API if algolia request fails.

---

azure-providers.js

More motivation on short names in azurestandard/api-spec@67cd688d
(public.json: Replace category's name and description with short-name
and name, 2015-02-12).

azure-providers.js: Use short names in category paths

---

azure-providers.js

Support azurestandard/api-spec#158.
This change causes set-cookie to work in the response to /registration/confirm. Without it, the cookie is ignored.
Blocking azurestandard/website#653.

Support azurestandard/api-spec#158.

---

README.md
azure-providers.js

The previous /purchase-orders API wasn't spec'ed, and
azurestandard/api-spec@21ec51e (public.json: Add 'GET /purchases' and
'GET /purchase/{id}', 2015-10-31, azurestandard/api-spec#49) is using
the shorter form.

Adjust to purchase-order -> purchase API rename

---

azure-providers.js

This change causes set-cookie to work in the response to
/registration/register and removes /registration/confirm.

Support azurestandard/api-spec#182

---

azure-providers.js

Previously we were just sorting by price.retail.dollars, regardless of variable-weight-ness.  For variable-weight products, that dollar value is per-pound, which was sorting bulkier, more efficient items earlier in the packaging list.  Our goal is to sort smaller, more expensive (per-pound) items earlier in the list because they have the prettiest pictures (bulk item pictures are usually just cardboard boxes).

AzureProduct: Sort variable-weight packaging by average retail price

---

README.md
azure-providers.js

Since azurestandard/api-spec#182), the registration email is no longer about confirming the registration.  Make the method name more generic (which also brings it closer to the endpoint's URL).

AzureAPI: Rename resendConfirmationEmail to resendRegistrationEmail

---

azure-providers.js

These were added in #62, although [we forgot to document them][1].  We've dropped those endpoints from the API in azurestandard/api-spec#195.
[1]: https://github.com/azurestandard/azure-angular-providers/pull/62#pullrequestreview-6923450

azure-providers: Drop AzureAPI.email.confirm and confirmResend

---

azure-providers.js
bower.json
package.json

added necessary post requests for the NMI three step redirect
The first is to separate the customer vault creation from the paymentmethod.py view.
The second is to accept the POST request sent back by NMI during step 3 of transactions.

added necessary post requests for the NMI three step redirect
